### ISSUE TITLE
allow non-looped cleanups

### ISSUE THREAD

**Issue by docteurklein** [meltwater/docker-cleanup#10]
hey there!
Is it possible to run this script "one-shot" ?
I'd like to run it, and once finished, exit.

**Comment by mikljohansson** [comment]
At the moment no, but a PR that adds a default "LOOP=true" flag which you can then set to "LOOP=false" would be most welcome!

**Comment by docteurklein** [comment]
awesome! thanks.

**Comment by salimane** [comment]
@docteurklein 1.4.1 has been released on docker hub

**Comment by docteurklein** [comment]
thanks,  that was super fast :)
already using it, seems to work great!
