### ISSUE TITLE
Unable to clean same unused images from multiple repositories

### ISSUE THREAD

**Issue by oomathias** [meltwater/docker-cleanup#19]
```
REPOSITORY                                           TAG                                        IMAGE ID            CREATED             SIZE
autodeploy                                           6ebe3bbe6cbed36f0c69cf87cbfb68aad14c62ba   9ffd283dcfcb        5 minutes ago       190.5 MB
x.x.io:443/ci/autodeploy                    6ebe3bbe6cbed36f0c69cf87cbfb68aad14c62ba   9ffd283dcfcb        5 minutes ago       190.5 MB
```

Both images are not used but `docker rmi 9ffd283dcfcb` doesn't work since they have the same ID. In this case it should be deleted by name.

```
2016-03-10T17:40:28.659207597Z => Start to clean 3 images
2016-03-10T17:40:28.679801771Z Error response from daemon: conflict: unable to delete 9ffd283dcfcb (must be forced) - image is referenced in one or more repositories
2016-03-10T17:40:28.680382797Z Error response from daemon: conflict: unable to delete 9ffd283dcfcb (must be forced) - image is referenced in one or more repositories
```

**Comment by willseward** [comment]
I see this too. Docker seems to handle the dependent images strangely. I was able to change the command to a `docker rmi -f` but you will have to run the command multiple times in order to remove all the unused images.

**Comment by mikljohansson** [comment]
Would you be willing to create and test a PR that adds the "-f" flag for the `docker rmi` commands used by the `run.sh` script?

**Comment by garceri** [comment]
The following modified run.sh script takes care of deleting images with duplicate ids 
[run.sh.txt](https://github.com/meltwater/docker-cleanup/files/534580/run.sh.txt)

**Comment by sorenroug** [comment]
I have made a patch in #37 that removes the image by it tags if it has one or more. That should fix it without using `-f`.

**Comment by MaRuifeng** [comment]
@oomathias You may try to remove the images explicitly from their repository names and tags like 

`docker images | grep -E 'autodeploy' | awk '{ print $1":"$2 }' | xargs --no-run-if-empty docker rmi`

**Comment by joeyhub** [comment]
The way to remove images in docker is currently:

    loop
        code = 0
        for each docker image ls | trim | split NL | shuffle as line
            cells = line | split \s+
            code |= docker image rm cells[[0, 2] | shuffle | pop]
        if not code
            break

If your images are dependent on anything other than images or image tags then this will loop infinitely. To stop that you instead must apply every possible permutation and compare the output of each loop. This also wont take into account tags but it does take into account tags.

**Comment by alonsoir** [comment]
docker rmi -f $(docker images -q) did the job in my laptop.

**Comment by abdullahawara** [comment]
Be careful! this will remove **all** images:
> docker rmi -f $(docker images -q) did the job in my laptop.

Source https://docs.docker.com/engine/reference/commandline/images/#options
