### ISSUE TITLE
Permission denied?

### ISSUE THREAD

**Issue by MrAtheist** [meltwater/docker-cleanup#23]
With the new release (1.7.0) im getting the following error:

```
$ docker run
   -v /var/run/docker.sock:/var/run/docker.sock:rw
   -v /var/lib/docker:/var/lib/docker:rw
   meltwater/docker-cleanup

exec: "/run.sh": permission denied
docker: Error response from daemon: Container command could not be invoked..
```

There's no problem with 1.6.0. Not sure what changes made in run.sh that require extra permission.

**Comment by mikljohansson** [comment]
The executable bit on the run.sh script got lost as part of PR #22. The github diff doesn't make the mode change terribly obvious, unfortunately it passed review. I've corrected this and released 1.7.1 that fixes this problem
