### ISSUE TITLE
cannot unmarshal object into Go value of type []string

### ISSUE THREAD

**Issue by sroze** [meltwater/docker-cleanup#28]
I'm experiencing a strange issue ATM, where I get the following logs from the containers:

```
docker is running properly
DEBUG ENABLED
=> Run the clean script every 60 seconds and delay 1800 seconds to clean.
DEBUG: Starting loop
=> Removing unused volumes using native 'docker volume' command
Error response from daemon: json: cannot unmarshal object into Go value of type []string
=> Removing exited/dead containers
Error response from daemon: json: cannot unmarshal object into Go value of type []string
=> Removing unused images
Error response from daemon: json: cannot unmarshal object into Go value of type []string
```

Here are the different Docker informations:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

The Docker daemon (`/var/log/docker.log`) also have these logs:

```
time="2016-06-13T11:06:38.415267697Z" level=error msg="Handler for GET /v1.21/volumes returned error: json: cannot unmarshal object into Go value of type []string" 
time="2016-06-13T11:06:38.415364606Z" level=error msg="HTTP Error" err="json: cannot unmarshal object into Go value of type []string" statusCode=500 
time="2016-06-13T11:06:38.434171019Z" level=error msg="Handler for GET /v1.21/containers/json returned error: json: cannot unmarshal object into Go value of type []string" 
time="2016-06-13T11:06:38.434265178Z" level=error msg="HTTP Error" err="json: cannot unmarshal object into Go value of type []string" statusCode=500 
time="2016-06-13T11:06:38.451053964Z" level=error msg="Handler for GET /v1.21/containers/json returned error: json: cannot unmarshal object into Go value of type []string" 
time="2016-06-13T11:06:38.451140106Z" level=error msg="HTTP Error" err="json: cannot unmarshal object into Go value of type []string" statusCode=500 
```

Anybody already experienced this issue?

Thank you very much,

**Comment by mikljohansson** [comment]
Haven't seen these problems before. Perhaps something on the docker daemon state that's gotten in a weird state. If possible could you try to stop the docker daemon and wipe /var/lib/docker/\* and then start docker daemon and try docker-cleanup again?

Disclaimer: Note that wiping /var/lib/docker/\* would remove all your volumes and containers.

**Comment by sroze** [comment]
I'm not sure if the problem is really on Docker side because the API looks to be fine as the `docker ps` command is working as expected. Also, it's running on many nodes and all of them have the same issue.

**Comment by sroze** [comment]
I can confirm this is an issue introduced here, as it's not working anymore with the `latest` tag with Docker 1.9.1 anymore. The setup didn't change, only the version of `meltwater/docker-cleanup`.

**Comment by sroze** [comment]
To follows up, it's working properly when using `meltwater/docker-cleanup:1.7.2`, released a month ago.

**Comment by rex** [comment]
@sroze You are my lifesaver right now. We're still running ancient 1.9.1 and I also ran into this strange problem. Explicitly declaring the version to `1.7.2` instead of `latest` got it running like a champ. Thank you!
