### ISSUE TITLE
sleep: invalid number ''3600''

### ISSUE THREAD

**Issue by abzmungul** [meltwater/docker-cleanup#3]
Hi when i change the default value of DELAY_TIME I get the following error in my logs. What could be causing this?

This is my unit file

[Unit]
Description=Cleanup of exited containers and unused images/volumes
After=docker.service
Requires=docker.service

[Install]
WantedBy=multi-user.target

[Service]
Environment=IMAGE=meltwater/docker-cleanup:latest NAME=docker-cleanup
# Allow docker pull to take some time

TimeoutStartSec=600
# Restart on failures

KillMode=none
Restart=always
RestartSec=15

ExecStartPre=-/usr/bin/docker kill $NAME
ExecStartPre=-/usr/bin/docker rm $NAME
ExecStartPre=-/bin/sh -c 'if ! docker images | tr -s " " : | grep "^${IMAGE}:"; then docker pull "${IMAGE}"; fi'
ExecStart=/usr/bin/docker run \
    -e CLEAN_PERIOD='3600' \
    -e DELAY_TIME='3600' \
    -v /var/run/docker.sock:/var/run/docker.sock:rw \
    -v /var/lib/docker:/var/lib/docker:rw \
    --name=${NAME} \
    $IMAGE

ExecStop=/usr/bin/docker stop $NAME

**Comment by mikljohansson** [comment]
Perhaps its the single quotes ' around the numbers in the docker run -e,
try removing them.

Systemd commands are executed directly and not in a surrounding shell, so
sh'ism like quoting and envvars unfortunately don't work the same in a unit
file as when you run it from a shell prompt.

Best,
Mikael

**Comment by mikljohansson** [comment]
I'm assuming the issue was the single quotes, please reply if that wasn't the case and we'll try and sort it out. 

Best regards, 
 Mikael

**Comment by abzmungul** [comment]
Thanks all working now :0)
