### ISSUE TITLE
Limit disk usage with LRU

### ISSUE THREAD

**Issue by kkvilekval** [meltwater/docker-cleanup#33]
Feature request:  Instead of deleting all unused images, have a  pool size that evicts based on LRU.  

This would be really useful when nodes are running all sorts of images but we would still like fast starts when.  

Context:  We run periodic jobs through a set of nodes.  We have a lot of images and the nodes don't have a large attached disk.. I would like to keep the last 16GB of recently used images, but remove all others to be able to run new jobs.

**Comment by rasjoh** [comment]
Won't fix due to retiring project
