### ISSUE TITLE
Does not remove images without -f parameter for docker rmi command

### ISSUE THREAD

**Issue by heikkis** [meltwater/docker-cleanup#34]
I found out that it does not remove any images. If -f is added to docker rmi command images will be removed then correctly. Reason was something like "because of tags try -f".

**Comment by oskapt** [comment]
Do not add `-f` to `docker rmi` arbitrarily. You will find that images you did not intend to remove are removed anyway. `-f` means `force`, and should be used carefully and only by intent. Never use this in a script.

I recommend that this issue be closed.

**Comment by rasjoh** [comment]
Won't fix due to retiring project
