### ISSUE TITLE
Support for overlay

### ISSUE THREAD

**Issue by ruseinov** [meltwater/docker-cleanup#9]
Right now this tool is aimed at vfs, coreos uses overlay, which doesn't really work in the same way, at least changing vfs/dir to overlay and running the script removes all sorts of things that break running containers.

I'm wondering if you investigated that subject already.

**Comment by mikljohansson** [comment]
We haven't really thought about that much, we use CentOS/RHEL in production and Ubuntu flavors on workstations. In recent Docker versions there's an actual volume API and CLI command which would perhaps be better to use than coding in knowledge about Docker filesystem internals. The docker-cleanup container can run without mapping /var/lib/docker in which case volumes won't be cleaned up (or corrupted as in your overlayfs case)

The volume cleanup script is actually copied verbatim from https://github.com/chadoe/docker-cleanup-volumes and just packaged into a Docker image for simplicity of deployment, there's a comment giving attribution at the top of our copy. 

@chadoe would perhaps be interested in improvement ideas and overlayfs or volume API support. We'd also be happy to incorporate such improvements into the docker-cleanup image.
